name: Upload Notebook → Colab → MDX → PR to oso repo

on:
  push:
    branches: [main]                       # only after PRs merge to main
    paths:
      - "tutorials/data-science/**/*.ipynb"  # notebooks to watch

permissions:
  contents: write
  pull-requests: write

jobs:
  process:
    runs-on: ubuntu-latest
    environment: deploy
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      COLAB_FOLDER_ID:    ${{ vars.COLAB_FOLDER_ID }}
      COLAB_DRIVE_ID:     ${{ vars.COLAB_DRIVE_ID }}
      GEMINI_API_KEY:     ${{ secrets.GEMINI_API_KEY }}


    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    - uses: actions/setup-python@v5
      with: { python-version: "3.10" }

    - name: Install deps
      run: |
        pip install nbconvert \
                   google-api-python-client \
                   google-auth google-auth-httplib2 google-auth-oauthlib \
                   google-genai

    #  list notebooks modified in this push
    - name: Find notebooks changed in this push
      id: list
      run: |
        NOTEBOOKS=$(git diff -M --name-only --diff-filter=AMR \
          "${{ github.event.before }}" "${{ github.sha }}" \
          | grep '\.ipynb$' || true)
    
        echo "notebooks<<EOF"   >> "$GITHUB_OUTPUT"
        echo "$NOTEBOOKS"        >> "$GITHUB_OUTPUT"
        echo "EOF"               >> "$GITHUB_OUTPUT"
    
        if [ -z "$NOTEBOOKS" ]; then
          echo "No new or modified .ipynb files; skipping workflow."
          exit 0
        fi

    # upload each notebook to colab + build MDX files 
    - name: Upload & convert to MDX
      if: steps.list.outputs.notebooks != '' 
      run: |
        mkdir -p mdx_build
        while read -r NB; do
          [ -z "$NB" ] && continue
          echo "Processing $NB"

          BASENAME="$(basename "$NB" .ipynb)"

          # Upload to Drive → Colab link
          LINK=$(python scripts/upload_to_drive.py "$NB" \
                  --folder "$COLAB_FOLDER_ID")

          # ipynb → markdown
          jupyter nbconvert "$NB" --to markdown --output "$BASENAME"

          MARKDOWN_PATH="$(dirname "$NB")/$BASENAME.md"
          MDX_OUT="mdx_build/${BASENAME}.mdx"

          printf '<a href="%s" target="_blank">Open in Colab</a>\n\n' "$LINK" >  "$MDX_OUT"
          cat "$MARKDOWN_PATH" >> "$MDX_OUT"
        done <<< "${{ steps.list.outputs.notebooks }}"

        # Stage into the folder structure that must exist in oso repo
        mkdir -p mdx_build/apps/docs/docs/tutorials
        mv mdx_build/*.mdx mdx_build/apps/docs/docs/tutorials/

    # grab the current index.md from oso repo
    - name: Update tutorials index with Gemini
      if: steps.list.outputs.notebooks != ''
      env:
        TARGET_PAT: ${{ secrets.TARGET_PAT }}
      run: python scripts/update_tutorial_index.py

    # clone oso, copy files, push branch
    - name: Push MDX files to oso repo
      if: steps.list.outputs.notebooks != ''
      env:
        PAT: ${{ secrets.TARGET_PAT }}
      run: |
        set -euo pipefail
        BRANCH="auto/tutorial-mdx-${{ github.run_id }}"
        OSO="opensource-observer/oso"

        echo "Cloning $OSO"
        git clone --depth=1 --branch main "https://${GITHUB_ACTOR}:${PAT}@github.com/${OSO}.git" oso-work
        cd oso-work

        git config user.email "github-actions@github.com"
        git config user.name  "github-actions"

        echo "Creating/updating branch $BRANCH"
        if git rev-parse --verify "origin/$BRANCH" >/dev/null 2>&1; then
          git checkout "$BRANCH"
        else
          git checkout -b "$BRANCH"
        fi

        echo "Copying MDX files into repo"
        rsync -a --delete \
          ../mdx_build/apps/docs/docs/tutorials/ \
          apps/docs/docs/tutorials/

        echo "Committing changes (if any)"
        if ! git diff --quiet; then
          git add apps/docs/docs/tutorials/
          git commit -m "docs: add auto-generated MDX tutorial(s)"
          git push --set-upstream origin "$BRANCH"
        else
          echo "No diff - nothing to commit."
        fi

    # open or update PR 
    - name: Open / update pull request in oso
      if: steps.list.outputs.notebooks != ''
      env:
        GH_TOKEN: ${{ secrets.TARGET_PAT }}   # PAT with write access to oso
      run: |
        set -euo pipefail
        BRANCH="auto/tutorial-mdx-${{ github.run_id }}"
        OSO="opensource-observer/oso"

        echo "📝 Creating (or updating) PR in $OSO"
        gh pr create \
          --repo "$OSO" \
          --head "$BRANCH" \
          --base main \
          --title "Add MDX tutorial(s) - run ${{ github.run_id }}" \
          --body "Auto-generated MDX files created from notebooks merged into **${{ github.repository }}**.\n\nPlease review; oso-repo CI must pass before merge." \
          --fill || true   # non-zero if PR already exists – that's fine
